SWAPI_L2_DESCRIPTOR = "sci"
ALPHA_TEMPERATURE_DENSITY_LOOKUP_TABLE_DESCRIPTOR = "alpha-density-temperature-lut"
GEOMETRIC_FACTOR_SW_LOOKUP_TABLE_DESCRIPTOR = "energy-gf-sw-lut"
GEOMETRIC_FACTOR_PUI_LOOKUP_TABLE_DESCRIPTOR = "energy-gf-pui-lut"
EFFICIENCY_LOOKUP_TABLE_DESCRIPTOR = "efficiency-lut"
INSTRUMENT_RESPONSE_LOOKUP_TABLE_DESCRIPTOR = "instrument-response-lut"
DENSITY_OF_NEUTRAL_HELIUM_DESCRIPTOR = "density-of-neutral-helium-lut"
HYDROGEN_INFLOW_VECTOR_DESCRIPTOR = "hydrogen-inflow-vector"
HELIUM_INFLOW_VECTOR_DESCRIPTOR = "helium-inflow-vector"

AZIMUTHAL_TRANSMISSION_DESCRIPTOR = "azimuthal-transmission"
CENTRAL_EFFECTIVE_AREA_DESCRIPTOR = "central-effective-area"
PASSBAND_FIT_COEFFICIENTS_DESCRIPTOR = "passband-fit-coefficients"

SWAPI_L3A_ALPHA_SW_DESCRIPTOR = "alpha-sw"

MAG_RTN_DESCRIPTOR = "norm-rtn"
