epoch:
  NAME: epoch
  DATA_TYPE: CDF_TIME_TT2000
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included for center of CR
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Epoch
  FORMAT: ' '
  LABLAXIS: Epoch
  UNITS: ns
  VALIDMIN: 2010-01-01T00:00:00.000000000
  VALIDMAX: 2099-12-31T00:00:00.000000000
  FILLVAL: 9999-12-31T23:59:59.999999999
  SCALETYP: linear
  TIME_BASE: J2000
  TIME_SCALE: TT
  DELTA_PLUS_VAR: epoch_delta
  DELTA_MINUS_VAR: epoch_delta
  MONOTON: INCREASE
  REFERENCE_POSITION: Rotating Earth Geoid
  SI_CONVERSION: 1e-9>seconds
epoch_delta:
  NAME: epoch_delta
  DATA_TYPE: CDF_INT8
  CATDESC: Time bin of half a carrington rotation
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Epoch Delta
  FORMAT: I19
  LABLAXIS: Epoch delta
  UNITS: ns
  VALIDMIN: 0
  VALIDMAX: 2592000000000000
  FILLVAL: -9223372036854775808
  SCALETYP: linear
mean_time:
  NAME: mean_time
  DATA_TYPE: CDF_TIME_TT2000
  CATDESC: Mean time of lightcurve data, number of nanoseconds since J2000 with leap seconds
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Mean Time
  FORMAT: ' '
  LABLAXIS: Mean Time
  UNITS: ns
  VALIDMIN: 2010-01-01T00:00:00.000000000
  VALIDMAX: 2099-12-31T00:00:00.000000000
  FILLVAL: 9999-12-31T23:59:59.999999999
  SCALETYP: linear
  TIME_BASE: J2000
  TIME_SCALE: TT
  MONOTON: INCREASE
  REFERENCE_POSITION: Rotating Earth Geoid
  SI_CONVERSION: 1e-9>seconds
cr:
  NAME: cr
  DATA_TYPE: CDF_INT2
  CATDESC: Carrington rotation number
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Carrington Rotation
  FORMAT: I14
  LABLAXIS: Carrington rotation
  UNITS: ' '
  VALIDMIN: 2000
  VALIDMAX: 3000
  FILLVAL: -32768
  SCALETYP: linear
uv_anisotropy_factor:
  NAME: uv_anisotropy_factor
  DATA_TYPE: CDF_FLOAT
  CATDESC: UV anisotropy factor
  DEPEND_0: epoch
  DEPEND_1: lat_grid
  VAR_NOTES: "Calculated directly at the grid point; not integrated over space."
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: UV Anisotropy Factor
  FORMAT: F9.3
  LABLAXIS: UV anisotropy factor
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 10
  FILLVAL: -1.00E+31
  SCALETYP: linear
  SCALEMIN: 0
  SCALEMAX: 10
lat_grid:
  NAME: lat_grid
  DATA_TYPE: CDF_FLOAT
  CATDESC: Latitudinal grid from -90 to 90
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: Latitude Grid
  FORMAT: F9.3
  LABLAXIS: Lat grid
  UNITS: degrees
  VALIDMIN: -90
  VALIDMAX: 90
  FILLVAL: -1.00E+31
  LABL_PTR_1: lat_grid_label
  SCALETYP: linear
sum_rate:
  NAME: sum_rate
  DATA_TYPE: CDF_FLOAT
  CATDESC: Averaged ionization rate profile obtained from lightcurve
  DEPEND_0: epoch
  DEPEND_1: lat_grid
  VAR_NOTES: "Calculated directly at the grid point; not integrated over space."
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: spectrogram
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Sum Rate
  FORMAT: F9.3
  LABLAXIS: Sum rate
  UNITS: s^-1
  VALIDMIN: 0
  VALIDMAX: 1.0
  FILLVAL: -1.00E+31
  SCALETYP: linear
  DELTA_PLUS_VAR: sum_uncert
  DELTA_MINUS_VAR: sum_uncert
  SCALEMIN: 0
  SCALEMAX: 1.0e-6
ph_rate:
  NAME: ph_rate
  DATA_TYPE: CDF_FLOAT
  CATDESC: Averaged photoionization rate profile
  DEPEND_0: epoch
  DEPEND_1: lat_grid
  VAR_NOTES: "Calculated directly at the grid point; not integrated over space."
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: spectrogram
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Photoionization Rate
  FORMAT: F9.3
  LABLAXIS: Photoionization rate
  UNITS: s^-1
  VALIDMIN: 0
  VALIDMAX: 1.0
  FILLVAL: -1.00E+31
  SCALETYP: linear
  DELTA_PLUS_VAR: ph_uncert
  DELTA_MINUS_VAR: ph_uncert
  SCALEMIN: 0
  SCALEMAX: 1.0e-6
cx_rate:
  NAME: cx_rate
  DATA_TYPE: CDF_FLOAT
  CATDESC: Averaged charge exchange rate profile (stationary atom approximation)
  DEPEND_0: epoch
  DEPEND_1: lat_grid
  VAR_NOTES: "Calculated directly at the grid point; not integrated over space."
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: spectrogram
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Charge Exchange Rate
  FORMAT: F9.3
  LABLAXIS: Charge exchange rate
  UNITS: s^-1
  VALIDMIN: 0
  VALIDMAX: 1.0
  FILLVAL: -1.00E+31
  SCALETYP: linear
  DELTA_PLUS_VAR: cx_uncert
  DELTA_MINUS_VAR: cx_uncert
  SCALEMIN: 0
  SCALEMAX: 1.0e-6
sum_uncert:
  NAME: sum_uncert
  DATA_TYPE: CDF_FLOAT
  CATDESC: Averaged ionization rate profile uncertainty
  DEPEND_0: epoch
  DEPEND_1: lat_grid
  VAR_NOTES: "Calculated directly at the grid point; not integrated over space."
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Sum Rate Uncertainty
  FORMAT: F9.3
  LABLAXIS: Sum rate uncertainty
  UNITS: s^-1
  VALIDMIN: 0
  VALIDMAX: 1.0
  FILLVAL: -1.00E+31
  SCALETYP: linear
ph_uncert:
  NAME: ph_uncert
  DATA_TYPE: CDF_FLOAT
  CATDESC: Averaged photoionization rate profile uncertainty
  DEPEND_0: epoch
  DEPEND_1: lat_grid
  VAR_NOTES: "Calculated directly at the grid point; not integrated over space."
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Photoionization Rate Uncertainty
  FORMAT: F9.3
  LABLAXIS: Photoionization rate uncertainty
  UNITS: s^-1
  VALIDMIN: 0
  VALIDMAX: 1.0
  FILLVAL: -1.00E+31
  SCALETYP: linear
cx_uncert:
  NAME: cx_uncert
  DATA_TYPE: CDF_FLOAT
  CATDESC: Averaged charge exchange rate profile uncertainty
  DEPEND_0: epoch
  DEPEND_1: lat_grid
  VAR_NOTES: "Calculated directly at the grid point; not integrated over space."
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Charge Exchange Rate Uncertainty
  FORMAT: F9.3
  LABLAXIS: Charge exchange rate uncertainty
  UNITS: s^-1
  VALIDMIN: 0
  VALIDMAX: 1.0
  FILLVAL: -1.00E+31
  SCALETYP: linear
lat_grid_label:
  NAME: lat_grid_label
  DATA_TYPE: CDF_CHAR
  CATDESC: Label for lat grid
  VAR_TYPE: metadata
  FIELDNAM: Latitude Grid Label
  FORMAT: a20
  FILLVAL: ' '
  UNITS: ' '
  RECORD_VARYING: NRV
uv_anisotropy_flag:
  NAME: uv_anisotropy_flag
  DATA_TYPE: CDF_INT2
  CATDESC: Source flag for UV anisotropy
  DEPEND_0: epoch
  VAR_TYPE: support_data
  FIELDNAM: UV Anisotropy Source
  FORMAT: I6
  LABLAXIS: UV anisotropy source
  VALIDMIN: -1
  VALIDMAX: 30000
  FILLVAL: -32768
  DISPLAY_TYPE: time_series
  SCALETYP: linear
  RECORD_VARYING: RV
  UNITS: ' '
  VAR_NOTES: >-
    Primarily for instrument team traceability. Details in release notes. Values:
    -1: Unspecified
    10000: Constant model
    20000: Pheomenological model
    20010: Pheomenological model 1
    20020: Pheomenological model 2
used_l3a:
  NAME: used_l3a
  DATA_TYPE: CDF_CHAR
  CATDESC: L3a files used
  VAR_TYPE: metadata
  FIELDNAM: Used L3a Files
  FORMAT: a50
  LABLAXIS: Used L3a
  FILLVAL: ' '
  DISPLAY_TYPE: no_plot
  RECORD_VARYING: RV
  UNITS: ' '
  DEPEND_0: epoch
glows_flags:
  NAME: glows_flags
  DATA_TYPE: CDF_UINT2
  CATDESC: "Quality flags for GLOWS L3b (caution required if nonzero)"
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  SCALETYP: linear
  FIELDNAM: Quality Flags for GLOWS L3b
  FORMAT: I5
  UNITS: '0: okay; nonzero: caution'
  VALIDMIN: 0
  VALIDMAX: 65534
  FILLVAL: 65535
  LABLAXIS: Quality flags for GLOWS L3b
  VAR_NOTES: >-
    Each bit corresponds to a specific potential concern. See release notes for details.
    All bits are reserved for future use.
