epoch:
  NAME: epoch
  DATA_TYPE: CDF_TIME_TT2000
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Epoch
  FORMAT: ' '
  LABLAXIS: Epoch
  UNITS: ns
  VALIDMIN: 1990-01-01T00:00:00.000000000
  VALIDMAX: 2099-12-31T00:00:00.000000000
  FILLVAL: 9999-12-31T23:59:59.999999999
  TIME_BASE: J2000
  TIME_SCALE: TT
  DELTA_PLUS_VAR: epoch_delta
  DELTA_MINUS_VAR: epoch_delta
  MONOTON: INCREASE
  REFERENCE_POSITION: Rotating Earth Geoid
  SCALETYP: linear
  SI_CONVERSION: 1e-9>seconds
epoch_delta:
  NAME: epoch_delta
  CATDESC: Epoch delta
  FIELDNAM: Epoch Delta
  DATA_TYPE: CDF_INT8
  FORMAT: I15
  UNITS: ns
  VALIDMIN: 0
  VALIDMAX: 999999999999999
  FILLVAL: -9223372036854775808
  SCALETYP: linear
  LABLAXIS: Epoch delta
  DEPEND_0: epoch
  RECORD_VARYING: RV
  VAR_TYPE: support_data
  VAR_NOTES: Time duration of the IMAP spacecraft pointing for which this grid is valid.
energy_grid:
  NAME: energy_grid
  DATA_TYPE: CDF_DOUBLE
  CATDESC: Energies associated with the survival probabilities for IMAP-Ultra
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: Energy
  FORMAT: g9.3
  LABLAXIS: Energy
  UNITS: keV
  VALIDMIN: 0
  VALIDMAX: 10000000000
  FILLVAL: -1.0000E+31
  SCALETYP: log
  DELTA_PLUS_VAR: energy_delta_plus
  DELTA_MINUS_VAR: energy_delta_minus
  VAR_NOTES: Calculated by interpolation to this specific point energy. Bin width is for ease of plotting and does not represent a range of measurement energies.
energy_delta_plus:
  NAME: energy_delta_plus
  DATA_TYPE: CDF_FLOAT
  CATDESC: Energies delta plus associated with the survival probabilities for IMAP-Ultra
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: Energy delta plus
  FORMAT: g9.3
  LABLAXIS: energy
  UNITS: keV
  VALIDMIN: 0
  VALIDMAX: 10000000000
  FILLVAL: -1.0000E+31
  SCALETYP: log
energy_delta_minus:
  NAME: energy_delta_minus
  DATA_TYPE: CDF_FLOAT
  CATDESC: Energies delta minus associated with the survival probabilities for IMAP-Ultra
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: Energy delta minus
  FORMAT: g9.3
  LABLAXIS: energy
  UNITS: keV
  VALIDMIN: 0
  VALIDMAX: 10000000000
  FILLVAL: -1.0000E+31
  SCALETYP: log
healpix_index:
  NAME: healpix_index
  DATA_TYPE: CDF_INT8
  CATDESC: Heal pixel index
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: HEALPix Index
  FORMAT: I19
  LABLAXIS: HEALPix index
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 3072
  FILLVAL: -9223372036854775808
surv_prob:
  NAME: surv_prob
  DATA_TYPE: CDF_FLOAT
  CATDESC: Survival probabilities for IMAP-Ultra
  VAR_TYPE: data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DEPEND_1: energy_grid
  DEPEND_2: healpix_index
  DISPLAY_TYPE: spectrogram
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Probability Of Survival
  FORMAT: g9.3
  LABLAXIS: Survival prob.
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 1
  FILLVAL: -1.0000E+31
  LABL_PTR_1: energy_label
  LABL_PTR_2: healpix_index_label
  VAR_NOTES: Calculated from model at given point in time, space, and energy.
spin_axis_latitude:
  NAME: spin_axis_latitude
  DATA_TYPE: CDF_FLOAT
  CATDESC: Latitude of spin axis
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  SCALETYP: linear
  FIELDNAM: Spin Axis Latitude
  LABLAXIS: Spin Axis Latitude
  FORMAT: F5.1
  FILLVAL: -1.0000E+31
  UNITS: degrees
  VALIDMIN: -90
  VALIDMAX: 90
spin_axis_longitude:
  NAME: spin_axis_longitude
  DATA_TYPE: CDF_FLOAT
  CATDESC: Longitude of spin axis
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Spin Axis Longitude
  LABLAXIS: Spin Axis Longitude
  FORMAT: F5.1
  FILLVAL: -1.0000E+31
  UNITS: degrees
  VALIDMIN: 0
  VALIDMAX: 360
energy_label:
  NAME: energy_label
  DATA_TYPE: CDF_CHAR
  CATDESC: Label for energy
  VAR_TYPE: metadata
  FIELDNAM: Energy Label
  FORMAT: a20
  LABLAXIS: Energy label
  FILLVAL: ' '
  UNITS: ' '
  RECORD_VARYING: NRV
healpix_index_label:
  NAME: healpix_index_label
  DATA_TYPE: CDF_CHAR
  CATDESC: Label for heal pixels
  VAR_TYPE: metadata
  FIELDNAM: HEALPix Index Label
  FORMAT: a20
  LABLAXIS: HEALPix index
  FILLVAL: ' '
  UNITS: ' '
  RECORD_VARYING: NRV
program_version:
  NAME: program_version
  DATA_TYPE: CDF_CHAR
  CATDESC: Program version
  VAR_TYPE: metadata
  FIELDNAM: Program Version
  FORMAT: a20
  FILLVAL: ' '
  UNITS: ' '
  RECORD_VARYING: NRV
spacecraft_radius:
  NAME: spacecraft_radius
  DATA_TYPE: CDF_FLOAT
  CATDESC: Distance from IMAP to sun
  DEPEND_0: epoch
  VAR_TYPE: support_data
  DISPLAY_TYPE: time_series
  SCALETYP: linear
  FIELDNAM: Spacecraft Radius
  LABLAXIS: Spacecraft Radius
  RECORD_VARYING: RV
  FORMAT: F4.2
  VALIDMIN: 0.0
  VALIDMAX: 1.1
  FILLVAL: -1.0000E+31
  UNITS: AU
spacecraft_latitude:
  NAME: spacecraft_latitude
  DATA_TYPE: CDF_FLOAT
  CATDESC: IMAP spacecraft latitude
  DEPEND_0: epoch
  VAR_TYPE: support_data
  DISPLAY_TYPE: time_series
  SCALETYP: linear
  FIELDNAM: Spacecraft Latitude
  LABLAXIS: Spacecraft Latitude
  RECORD_VARYING: RV
  FORMAT: F5.1
  FILLVAL: -1.0000E+31
  UNITS: degrees
  VALIDMIN: -90
  VALIDMAX: 90
spacecraft_longitude:
  NAME: spacecraft_longitude
  DATA_TYPE: CDF_FLOAT
  CATDESC: IMAP spacecraft longitude
  DEPEND_0: epoch
  VAR_TYPE: support_data
  DISPLAY_TYPE: time_series
  SCALETYP: linear
  FIELDNAM: Spacecraft Longitude
  LABLAXIS: Spacecraft Longitude
  RECORD_VARYING: RV
  FORMAT: F5.1
  FILLVAL: -1.0000E+31
  UNITS: degrees
  VALIDMIN: 0
  VALIDMAX: 360
spacecraft_velocity_x:
  NAME: spacecraft_velocity_x
  DATA_TYPE: CDF_FLOAT
  CATDESC: IMAP spacecraft x velocity
  DEPEND_0: epoch
  VAR_TYPE: support_data
  DISPLAY_TYPE: time_series
  SCALETYP: linear
  FIELDNAM: Spacecraft Velocity X
  LABLAXIS: Spacecraft Velocity X
  RECORD_VARYING: RV
  FORMAT: F6.2
  FILLVAL: -1.0000E+31
  UNITS: km/s
  VALIDMIN: -50
  VALIDMAX: 50
spacecraft_velocity_y:
  NAME: spacecraft_velocity_y
  DATA_TYPE: CDF_FLOAT
  CATDESC: IMAP spacecraft y velocity
  DEPEND_0: epoch
  VAR_TYPE: support_data
  DISPLAY_TYPE: time_series
  SCALETYP: linear
  FIELDNAM: Spacecraft Velocity Y
  LABLAXIS: Spacecraft Velocity Y
  RECORD_VARYING: RV
  FORMAT: F6.2
  FILLVAL: -1.0000E+31
  UNITS: km/s
  VALIDMIN: -50
  VALIDMAX: 50
spacecraft_velocity_z:
  NAME: spacecraft_velocity_z
  DATA_TYPE: CDF_FLOAT
  CATDESC: IMAP spacecraft z velocity
  DEPEND_0: epoch
  VAR_TYPE: support_data
  DISPLAY_TYPE: time_series
  SCALETYP: linear
  FIELDNAM: Spacecraft Velocity Z
  LABLAXIS: Spacecraft Velocity Z
  RECORD_VARYING: RV
  FORMAT: F6.2
  FILLVAL: -1.0000E+31
  UNITS: km/s
  VALIDMIN: -50
  VALIDMAX: 50
elongation_excluded:
  NAME: elongation_excluded
  DATA_TYPE: CDF_UINT2
  CATDESC: Region of excluded values from Ultra instrument
  VAR_TYPE: support_data
  FIELDNAM: Elongation Excluded
  LABLAXIS: Elongation excluded
  DEPEND_0: epoch
  FORMAT: I3
  UNITS: degree
  FILLVAL: 65535
  VALIDMAX: 180
  VALIDMIN: 0
  RECORD_VARYING: RV
pixel_longitude:
  NAME: pixel_longitude
  DEPEND_0: epoch
  DEPEND_1: healpix_index
  DATA_TYPE: CDF_FLOAT
  CATDESC: Pixel center longitude in HAE (ECLIPJ2000)
  VAR_NOTES: Reference frames are defined according to IMAP mission SPICE kernels.
  VAR_TYPE: support_data
  FIELDNAM: HAE longitude
  LABLAXIS: Longitude
  RECORD_VARYING: RV
  FORMAT: F5.1
  FILLVAL: -1.0000E+31
  UNITS: degrees
  VALIDMIN: 0
  VALIDMAX: 360
pixel_latitude:
  NAME: pixel_latitude
  DEPEND_0: epoch
  DEPEND_1: healpix_index
  DATA_TYPE: CDF_FLOAT
  CATDESC: Pixel center latitude in HAE (ECLIPJ2000)
  VAR_NOTES: Reference frames are defined according to IMAP mission SPICE kernels.
  VAR_TYPE: support_data
  FIELDNAM: HAE latitude
  LABLAXIS: Latitude
  RECORD_VARYING: RV
  FORMAT: F5.1
  FILLVAL: -1.0000E+31
  UNITS: degrees
  VALIDMIN: -90
  VALIDMAX: 90
glows_flags:
  NAME: glows_flags
  DATA_TYPE: CDF_UINT2
  CATDESC: "Quality flags for GLOWS L3e Ultra HF (caution required if nonzero)"
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  SCALETYP: linear
  FIELDNAM: Quality Flags for GLOWS L3e Ultra HF
  FORMAT: I5
  UNITS: '0: okay; nonzero: caution'
  VALIDMIN: 0
  VALIDMAX: 65534
  FILLVAL: 65535
  LABLAXIS: Quality flags for GLOWS L3e Ultra HF
  VAR_NOTES: >-
    Each bit corresponds to a specific potential concern. See release notes for details.
    Bit 2: Solar wind alpha/proton density ratio not available in OMNI data; input GLOWS L3c file used nominal value of 0.04.
    Bit 3: Indicates that the last calculated CR in L3d was repeated to later CRs that could not be computed 
    Bit 15: Indicates predictive ephemeris was used instead of reconstructed ephemeris.
    Other bits are reserved.
