epoch:
  NAME: epoch
  DATA_TYPE: CDF_TIME_TT2000
  CATDESC: Map time range start, number of nanoseconds since J2000 with leap seconds included
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: J2000 Nanoseconds
  FORMAT: ' '
  LABLAXIS: Epoch
  UNITS: ns
  VALIDMIN: 2010-01-01T00:00:00.000000000
  VALIDMAX: 2099-12-31T00:00:00.000000000
  FILLVAL: 9999-12-31T23:59:59.999999999
  SCALETYP: linear
  TIME_BASE: J2000
  TIME_SCALE: TT
  BIN_LOCATION: 0
  DELTA_PLUS_VAR: epoch_delta
  MONOTON: INCREASE
  REFERENCE_POSITION: Rotating Earth Geoid
  SI_CONVERSION: 1e-9>seconds
epoch_delta:
  NAME: epoch_delta
  DATA_TYPE: CDF_INT8
  CATDESC: Epoch delta
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Epoch Delta
  FORMAT: I19
  LABLAXIS: Epoch delta
  UNITS: ns
  VALIDMIN: 0
  VALIDMAX: 31536000000000000
  FILLVAL: -9223372036854775808
  SCALETYP: linear
energy:
  NAME: energy
  DATA_TYPE: CDF_REAL4
  CATDESC: Geometric mean of energy channel bounds
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: Energy
  FORMAT: F6.2
  LABLAXIS: Energy
  UNITS: keV
  VALIDMIN: 0.0
  VALIDMAX: 100.0
  FILLVAL: -1.00E+31
  SCALETYP: linear
  DELTA_PLUS_VAR: energy_delta_plus
  DELTA_MINUS_VAR: energy_delta_minus
  MONOTON: INCREASE
energy_label:
  NAME: energy_label
  DATA_TYPE: CDF_CHAR
  CATDESC: Label variable for energy coordinate
  DEPEND_1: energy
  VAR_TYPE: metadata
  FIELDNAM: Energy Label
  FORMAT: A16
  FILLVAL: ' '
energy_delta_minus:
  NAME: energy_delta_minus
  DATA_TYPE: CDF_REAL4
  CATDESC: Delta between the geometric mean and lower bound of the energy passband
  DEPEND_1: energy
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: Energy Delta Minus
  FORMAT: F6.2
  LABLAXIS: Energy delta minus
  UNITS: keV
  VALIDMIN: 0.0
  VALIDMAX: 100.0
  FILLVAL: -1.00E+31
  SCALETYP: linear
energy_delta_plus:
  NAME: energy_delta_plus
  DATA_TYPE: CDF_REAL4
  CATDESC: delta between the geometric mean and upper bound of the energy passband
  DEPEND_1: energy
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: Energy Delta Plus
  FORMAT: F6.2
  LABLAXIS: Energy delta plus
  UNITS: keV
  VALIDMIN: 0.0
  VALIDMAX: 100.0
  FILLVAL: -1.00E+31
  SCALETYP: linear
latitude:
  NAME: latitude
  DATA_TYPE: CDF_REAL4
  CATDESC: Pixel center latitude
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: HAE Latitude
  FORMAT: I2
  LABLAXIS: Latitude
  UNITS: degrees
  VALIDMIN: -90.0
  VALIDMAX: 90.0
  FILLVAL: -1.00E+31
  SCALETYP: linear
  DELTA_PLUS_VAR: latitude_delta
  DELTA_MINUS_VAR: latitude_delta
  MONOTON: INCREASE
latitude_label:
  NAME: latitude_label
  DATA_TYPE: CDF_CHAR
  CATDESC: Label variable for latitude
  DEPEND_1: latitude
  VAR_TYPE: metadata
  FIELDNAM: Latitude Label
  FORMAT: A16
  FILLVAL: ' '
latitude_delta:
  NAME: latitude_delta
  DATA_TYPE: CDF_REAL4
  CATDESC: Half-width of latitude pixel
  DEPEND_1: latitude
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: Latitude Delta
  FORMAT: I3
  LABLAXIS: Latitude delta
  UNITS: degrees
  VALIDMIN: 0.0
  VALIDMAX: 90.0
  FILLVAL: -1.00E+31
  SCALETYP: linear
longitude:
  NAME: longitude
  DATA_TYPE: CDF_REAL4
  CATDESC: Pixel center longitude
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: HAE Longitude
  FORMAT: I3
  LABLAXIS: Longitude
  UNITS: degrees
  VALIDMIN: 0.0
  VALIDMAX: 360.0
  FILLVAL: -1.00E+31
  SCALETYP: linear
  DELTA_PLUS_VAR: longitude_delta
  DELTA_MINUS_VAR: longitude_delta
  MONOTON: INCREASE
longitude_label:
  NAME: longitude_label
  DATA_TYPE: CDF_CHAR
  CATDESC: Label variable for longitude
  DEPEND_1: longitude
  VAR_TYPE: metadata
  FIELDNAM: Longitude label
  FORMAT: A16
  FILLVAL: ' '
longitude_delta:
  NAME: longitude_delta
  DATA_TYPE: CDF_REAL4
  CATDESC: Half-width of longitude pixel
  DEPEND_1: longitude
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: Longitude Delta
  FORMAT: I3
  LABLAXIS: Longitude delta
  UNITS: degrees
  VALIDMIN: 0
  VALIDMAX: 180.0
  FILLVAL: -1.00E+31
ena_intensity:
  NAME: ena_intensity
  DATA_TYPE: CDF_REAL4
  CATDESC: Mono-energetic ENA intensity.
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: longitude
  DEPEND_3: latitude
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: map_image
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Intensity
  FORMAT: F12.1
  LABLAXIS: Intensity
  UNITS: cm -2 s -1 sr -1 keV -1
  VALIDMIN: 0.0
  VALIDMAX: 1.00E+9
  FILLVAL: -1.00E+31
  LABL_PTR_1: energy_label
  LABL_PTR_2: longitude_label
  LABL_PTR_3: latitude_label
  DELTA_PLUS_VAR: ena_intensity_stat_uncert
  DELTA_MINUS_VAR: ena_intensity_stat_uncert
  SCALETYP: linear
ena_intensity_stat_uncert:
  NAME: ena_intensity_stat_uncert
  DATA_TYPE: CDF_REAL4
  CATDESC: ENA intensity statistical uncertainty.
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: longitude
  DEPEND_3: latitude
  VAR_TYPE: support_data
  DISPLAY_TYPE: map_image
  RECORD_VARYING: RV
  FIELDNAM: Intensity Stat Unc
  FORMAT: F12.1
  LABLAXIS: Statistical unc.
  UNITS: cm -2 s -1 sr -1 keV -1
  VALIDMIN: 0.0
  VALIDMAX: 1.00E+9
  FILLVAL: -1.00E+31
  LABL_PTR_1: energy_label
  LABL_PTR_2: longitude_label
  LABL_PTR_3: latitude_label
  SCALETYP: linear
ena_intensity_sys_err:
  NAME: ena_intensity_sys_err
  DATA_TYPE: CDF_REAL4
  CATDESC: ENA intensity non-statistical error.
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: longitude
  DEPEND_3: latitude
  VAR_TYPE: support_data
  DISPLAY_TYPE: map_image
  RECORD_VARYING: RV
  FIELDNAM: Intensity Non-stat Error
  FORMAT: F12.1
  LABLAXIS: Non-statistical Error
  UNITS: cm -2 s -1 sr -1 keV -1
  VALIDMIN: 0.0
  VALIDMAX: 1.00E+9
  FILLVAL: -1.00E+31
  LABL_PTR_1: energy_label
  LABL_PTR_2: longitude_label
  LABL_PTR_3: latitude_label
  SCALETYP: linear
exposure_factor:
  NAME: exposure_factor
  DATA_TYPE: CDF_REAL4
  CATDESC: Exact or approximate exposure time over which counts in a pixel are accumulated.
  VAR_NOTES: Exact or approximate exposure time over which counts in a pixel are accumulated.  Used as a weighting factor for combining data quantities sensibly.
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: longitude
  DEPEND_3: latitude
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: no_plot
  FIELDNAM: Exposure Times
  VARIABLE_PURPOSE: ' '
  FORMAT: F5.2
  LABLAXIS: Exposure
  UNITS: s
  VALIDMIN: 0.0
  VALIDMAX: 1.00E+9
  FILLVAL: -1.00E+31
  LABL_PTR_1: energy_label
  LABL_PTR_2: longitude_label
  LABL_PTR_3: latitude_label
  SCALETYP: linear
obs_date:
  NAME: obs_date
  DATA_TYPE: CDF_TIME_TT2000
  CATDESC: Mean collection date of data in a pixel
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: longitude
  DEPEND_3: latitude
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DISPLAY_TYPE: no_plot
  FIELDNAM: J2000 Nanoseconds
  VARIABLE_PURPOSE: ' '
  FORMAT: ' '
  LABLAXIS: Epoch
  UNITS: ns
  VALIDMIN: 2010-01-01T00:00:00.000000000
  VALIDMAX: 2099-12-31T00:00:00.000000000
  FILLVAL: 9999-12-31T23:59:59.999999999
  LABL_PTR_1: energy_label
  LABL_PTR_2: longitude_label
  LABL_PTR_3: latitude_label
  SCALETYP: linear
obs_date_range:
  NAME: obs_date_range
  DATA_TYPE: CDF_INT8
  CATDESC: Standard deviation of the observation date
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: longitude
  DEPEND_3: latitude
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DISPLAY_TYPE: no_plot
  FIELDNAM: J2000 Nanoseconds
  VARIABLE_PURPOSE: ' '
  FORMAT: I19
  LABLAXIS: Epoch
  UNITS: ns
  VALIDMIN: 0
  VALIDMAX: 31536000000000000
  FILLVAL: -9223372036854775808
  LABL_PTR_1: energy_label
  LABL_PTR_2: longitude_label
  LABL_PTR_3: latitude_label
  SCALETYP: linear
solid_angle:
  NAME: solid_angle
  DATA_TYPE: CDF_REAL4
  CATDESC: Solid angle of subtended by each pixel
  DEPEND_1: longitude
  DEPEND_2: latitude
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  DISPLAY_TYPE: no_plot
  FIELDNAM: Solid Angle
  VARIABLE_PURPOSE: ' '
  FORMAT: F6.2
  LABLAXIS: Solid angle
  UNITS: sr
  VALIDMIN: 0.0
  VALIDMAX: 12.56637061
  FILLVAL: -1.00E+31
  LABL_PTR_1: longitude_label
  LABL_PTR_2: latitude_label
  SCALETYP: linear
ena_spectral_index:
  NAME: ena_spectral_index
  DATA_TYPE: CDF_REAL4
  CATDESC: ENA spectral index.
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: longitude
  DEPEND_3: latitude
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: map_image
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Spectral Index
  FORMAT: F12.6
  LABLAXIS: spectral index
  UNITS: ' '
  VALIDMIN: 0.0
  VALIDMAX: 100
  FILLVAL: -1.00E+31
  LABL_PTR_1: energy_label
  LABL_PTR_2: longitude_label
  LABL_PTR_3: latitude_label
  SCALETYP: linear
  DELTA_PLUS_VAR: ena_spectral_index_stat_uncert
  DELTA_MINUS_VAR: ena_spectral_index_stat_uncert
ena_spectral_index_stat_uncert:
  NAME: ena_spectral_index_stat_uncert
  DATA_TYPE: CDF_REAL4
  CATDESC: ENA spectral index statistical uncertainty.
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: longitude
  DEPEND_3: latitude
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: map_image
  FIELDNAM: Spectral Index Stat Unc
  VARIABLE_PURPOSE: ' '
  FORMAT: F12.6
  LABLAXIS: Statistical unc.
  UNITS: ' '
  VALIDMIN: 0.0
  VALIDMAX: 100
  FILLVAL: -1.00E+31
  LABL_PTR_1: energy_label
  LABL_PTR_2: longitude_label
  LABL_PTR_3: latitude_label
  SCALETYP: linear
  VAR_NOTES: Calculated by propagating ENA intensity statistical uncertainty through Levenberg-Marquardt fitting
ena_spectral_scalar:
  NAME: ena_spectral_scalar
  DATA_TYPE: CDF_REAL4
  CATDESC: ENA spectral index scalar coefficient.
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: longitude
  DEPEND_3: latitude
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: map_image
  VARIABLE_PURPOSE: ' '
  FIELDNAM: Spectral scalar
  FORMAT: F12.6
  LABLAXIS: Spectral scalar
  UNITS: cm -2 s -1 sr -1 keV -1
  VALIDMIN: 0.0
  VALIDMAX: 1.0E+20
  FILLVAL: -1.00E+31
  LABL_PTR_1: energy_label
  LABL_PTR_2: longitude_label
  LABL_PTR_3: latitude_label
  SCALETYP: log
  DELTA_PLUS_VAR: ena_spectral_scalar_stat_uncert
  DELTA_MINUS_VAR: ena_spectral_scalar_stat_uncert
ena_spectral_scalar_stat_uncert:
  NAME: ena_spectral_scalar_stat_uncert
  DATA_TYPE: CDF_REAL4
  CATDESC: ENA spectral index scalar coefficient statistical uncertainty.
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: longitude
  DEPEND_3: latitude
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: map_image
  VARIABLE_PURPOSE: ' '
  FIELDNAM: Spectral scalar stat unc
  FORMAT: F12.6
  LABLAXIS: Statistical unc.
  UNITS: cm -2 s -1 sr -1 keV -1
  VALIDMIN: 0.0
  VALIDMAX: 1.0E+20
  FILLVAL: -1.00E+31
  LABL_PTR_1: energy_label
  LABL_PTR_2: longitude_label
  LABL_PTR_3: latitude_label
  SCALETYP: log
  VAR_NOTES: Calculated by propagating ENA intensity statistical uncertainty through Levenberg-Marquardt fitting
ena_spectral_index_chisq:
  NAME: ena_spectral_index_chisq
  DATA_TYPE: CDF_REAL4
  CATDESC: ENA spectral index reduced chi-squared
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: longitude
  DEPEND_3: latitude
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: map_image
  VARIABLE_PURPOSE: ' '
  FIELDNAM: Spectral Index Chi-Squared
  FORMAT: F12.6
  LABLAXIS: spectral index chi-sq
  UNITS: ' '
  VALIDMIN: 0.0
  VALIDMAX: 1000000.0
  SCALEMIN: 0.0
  SCALEMAX: 10.0
  FILLVAL: -1.00E+31
  LABL_PTR_1: energy_label
  LABL_PTR_2: longitude_label
  LABL_PTR_3: latitude_label
  SCALETYP: linear
survival_probability:
  NAME: survival_probability
  DATA_TYPE: CDF_REAL4
  CATDESC: Survival Probability Map
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: longitude
  DEPEND_3: latitude
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: map_image
  VARIABLE_PURPOSE: ' '
  FIELDNAM: Survival Probability
  FORMAT: F12.6
  LABLAXIS: survival probability
  UNITS: ' '
  VALIDMIN: 0.0
  VALIDMAX: 1.0
  SCALEMIN: 0.0
  SCALEMAX: 1.0
  FILLVAL: -1.00E+31
  LABL_PTR_1: energy_label
  LABL_PTR_2: longitude_label
  LABL_PTR_3: latitude_label
  SCALETYP: linear
quality_flags:
  NAME: quality_flags
  DATA_TYPE: CDF_UINT2
  CATDESC: "Quality flags for Ultra (caution required if nonzero)"
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: longitude
  DEPEND_3: latitude
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: map_image
  SCALETYP: linear
  FIELDNAM: Quality Flags for Ultra
  FORMAT: I5
  UNITS: '0: okay; nonzero: caution'
  VALIDMIN: 0
  VALIDMAX: 65534
  FILLVAL: 65535
  LABLAXIS: Quality flags for Ultra
  VAR_NOTES: >-
    Each bit corresponds to a specific potential concern. See release notes for details.
    Bit 2: Survival probability was calculated using a nominal Solar wind alpha/proton density ratio.
    Bit 3: Survival probability was calculated from GLOWS L3d data that was repeated from previous CRs. 
    Bit 15: Survival probability calculated using predicted ephemeris.