epoch:
  NAME: epoch
  DATA_TYPE: CDF_TIME_TT2000
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included for center of CR
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Epoch
  FORMAT: ' '
  LABLAXIS: Epoch
  UNITS: ns
  VALIDMIN: 1947-01-01T00:00:00.000000000
  VALIDMAX: 2099-12-31T00:00:00.000000000
  FILLVAL: 9999-12-31T23:59:59.999999999
  SCALETYP: linear
  TIME_BASE: J2000
  TIME_SCALE: TT
  DELTA_PLUS_VAR: epoch_delta
  DELTA_MINUS_VAR: epoch_delta
  MONOTON: INCREASE
  REFERENCE_POSITION: Rotating Earth Geoid
  SI_CONVERSION: 1e-9>seconds
epoch_delta:
  NAME: epoch_delta
  DATA_TYPE: CDF_INT8
  CATDESC: Time bin of half a carrington rotation
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Epoch Delta
  FORMAT: I19
  LABLAXIS: Epoch delta
  UNITS: ns
  VALIDMIN: 0
  VALIDMAX: 2592000000000000
  FILLVAL: -9223372036854775808
  SCALETYP: linear
lat_grid:
  NAME: lat_grid
  DATA_TYPE: CDF_DOUBLE
  CATDESC: Latitudes from -90 to 90
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: Latitude
  FORMAT: F9.3
  LABLAXIS: Latitude
  UNITS: degrees
  VALIDMIN: -90
  VALIDMAX: 90
  FILLVAL: -1.00E+31
  SCALETYP: linear
cr_grid:
  NAME: cr_grid
  DATA_TYPE: CDF_DOUBLE
  CATDESC: Carrington rotation number
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Carrington Rotation
  FORMAT: F9.3
  LABLAXIS: Carrington rotation
  UNITS: ' '
  VALIDMIN: 1000
  VALIDMAX: 3000
  FILLVAL: -1.00E+31
  SCALETYP: linear
plasma_speed:
  NAME: plasma_speed
  DATA_TYPE: CDF_DOUBLE
  CATDESC: Solar wind plasma speed
  VAR_TYPE: data
  RECORD_VARYING: RV
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Plasma Speed
  FORMAT: F9.3
  LABLAXIS: Plasma speed
  DISPLAY_TYPE: spectrogram
  UNITS: km/s
  VALIDMIN: 0
  VALIDMAX: 10000
  FILLVAL: -1.00E+31
  SCALETYP: linear
  DEPEND_0: epoch
  DEPEND_1: lat_grid
  LABL_PTR_1: lat_grid_label
proton_density:
  NAME: proton_density
  DATA_TYPE: CDF_DOUBLE
  CATDESC: Solar wind proton density
  VAR_TYPE: data
  RECORD_VARYING: RV
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Proton Density
  FORMAT: F9.3
  LABLAXIS: Proton density
  DISPLAY_TYPE: spectrogram
  UNITS: '#/cm^3'
  VALIDMIN: 0
  VALIDMAX: 100
  FILLVAL: -1.00E+31
  SCALETYP: linear
  DEPEND_0: epoch
  DEPEND_1: lat_grid
  LABL_PTR_1: lat_grid_label
uv_anisotropy:
  NAME: uv_anisotropy
  DATA_TYPE: CDF_DOUBLE
  CATDESC: Solar UV radiation anisotropy
  VAR_TYPE: data
  RECORD_VARYING: RV
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Solar UV Anisotropy
  FORMAT: F9.3
  LABLAXIS: Solar UV Anisotropy
  DISPLAY_TYPE: spectrogram
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 1.00E+01
  FILLVAL: -1.00E+31
  SCALETYP: linear
  DEPEND_0: epoch
  DEPEND_1: lat_grid
  LABL_PTR_1: lat_grid_label
phion:
  NAME: phion
  DATA_TYPE: CDF_DOUBLE
  CATDESC: Photoionization rate in the ecliptic plane
  VAR_TYPE: data
  RECORD_VARYING: RV
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Photoionization Rate
  FORMAT: E7.1E2
  LABLAXIS: Photoionization rate
  DISPLAY_TYPE: time_series
  UNITS: '#/s'
  VALIDMIN: 0
  VALIDMAX: 1.00E-05
  FILLVAL: -1.00E+31
  SCALETYP: linear
  DEPEND_0: epoch
lyman_alpha:
  NAME: lyman_alpha
  DATA_TYPE: CDF_DOUBLE
  CATDESC: Composite solar Lyman-alpha irradiance
  VAR_TYPE: data
  RECORD_VARYING: RV
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Solar Lyman-alpha
  FORMAT: F14.3
  LABLAXIS: Solar Lyman-alpha
  DISPLAY_TYPE: time_series
  UNITS: '#/cm^2/s'
  VALIDMIN: 0
  VALIDMAX: 10000000000000
  FILLVAL: -1.00E+31
  SCALETYP: linear
  DEPEND_0: epoch
electron_density:
  NAME: electron_density
  DATA_TYPE: CDF_DOUBLE
  CATDESC: Electron density
  VAR_TYPE: data
  RECORD_VARYING: RV
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Electron Density
  FORMAT: F9.3
  LABLAXIS: Electron density
  DISPLAY_TYPE: time_series
  UNITS: '#/cm^3'
  VALIDMIN: 0
  VALIDMAX: 100
  FILLVAL: -1.00E+31
  SCALETYP: linear
  DEPEND_0: epoch
lat_grid_label:
  NAME: lat_grid_label
  DATA_TYPE: CDF_CHAR
  CATDESC: Label variable for latitude coordinate
  DEPEND_1: lat_grid
  VAR_TYPE: metadata
  FIELDNAM: Latitude Label
  FORMAT: A16
  FILLVAL: ' '
  RECORD_VARYING: NRV
  UNITS: ' '
plasma_speed_flag:
  NAME: plasma_speed_flag
  DATA_TYPE: CDF_INT4
  CATDESC: Solar wind plasma speed source
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  FIELDNAM: Plasma Speed Source
  FORMAT: I6
  LABLAXIS: Plasma speed source
  VALIDMIN: -1
  VALIDMAX: 100000
  FILLVAL: -2147483648
  UNITS: ' '
  VAR_NOTES: >-
    Primarily for instrument team traceability. Details in release notes. Values:
    -1: Unspecified
    20000: Speed from GLOWS measurements and ancillary inputs
    20001: Speed interpolated
    88888: Value extrapolated by repeating previous measured value
uv_anisotropy_flag:
  NAME: uv_anisotropy_flag
  DATA_TYPE: CDF_INT4
  CATDESC: Ultraviolet anisotropy source
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  FIELDNAM: UV Anisotropy Source
  FORMAT: I6
  LABLAXIS: UV anisotropy source
  VALIDMIN: -1
  VALIDMAX: 100000
  FILLVAL: -2147483648
  UNITS: ' '
  VAR_NOTES: >-
    Primarily for instrument team traceability. Details in release notes. Values:
    -1: Unspecified
    10000: Constant model
    20000: Pheomenological model
    20010: Pheomenological model 1
    20020: Pheomenological model 2
    30001: UV anisotropy interpolated
    88888: Value extrapolated by repeating previous measured value
proton_density_flag:
  NAME: proton_density_flag
  DATA_TYPE: CDF_INT4
  CATDESC: Solar wind proton density source
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  FIELDNAM: Proton Density Source
  FORMAT: I6
  LABLAXIS: Proton density source
  VALIDMIN: -1
  VALIDMAX: 100000
  FILLVAL: -2147483648
  UNITS: ' '
  VAR_NOTES: >-
    Primarily for instrument team traceability. Details in release notes. Values:
    -1: Unspecified
    10000: Density from same source as speed data
    10001: Density from source of speed data, interpolated
    88888: Value extrapolated by repeating previous measured value
glows_flags:
  NAME: glows_flags
  DATA_TYPE: CDF_UINT2
  CATDESC: "Quality flags for GLOWS L3d (caution required if nonzero)"
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  SCALETYP: linear
  FIELDNAM: Quality Flags for GLOWS L3d
  FORMAT: I5
  UNITS: '0: okay; nonzero: caution'
  VALIDMIN: 0
  VALIDMAX: 65534
  FILLVAL: 65535
  LABLAXIS: Quality flags for GLOWS L3d
  VAR_NOTES: >-
    Each bit corresponds to a specific potential concern. See release notes for details.
    Bit 2: Solar wind alpha/proton density ratio not available in OMNI data; input GLOWS L3c file used nominal value of 0.04.
    Bit 3: Indicates that the last calculated CR in L3d was repeated to later CRs that could not be computed 
    Other bits are reserved.
