epoch:
  NAME: epoch
  DATA_TYPE: CDF_TIME_TT2000
  FIELDNAM: Epoch
  CATDESC: Center-of-window time, number of nanoseconds since J2000 with leap seconds included
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: ' '
  LABLAXIS: Epoch
  UNITS: ns
  VALIDMIN: 2010-01-01T00:00:00.000000000
  VALIDMAX: 2099-12-31T00:00:00.000000000
  FILLVAL: 9999-12-31T23:59:59.999999999
  SCALETYP: linear
  TIME_BASE: J2000
  TIME_SCALE: TT
  DELTA_PLUS_VAR: epoch_delta
  DELTA_MINUS_VAR: epoch_delta
  MONOTON: INCREASE
  REFERENCE_POSITION: Rotating Earth Geoid
  SI_CONVERSION: 1e-9>seconds
epoch_delta:
  NAME: epoch_delta
  DATA_TYPE: CDF_INT8
  FIELDNAM: Epoch Delta
  CATDESC: Half-width of the time interval represented by each record
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: I19
  UNITS: ns
  VALIDMIN: 0
  VALIDMAX: 86000000000000
  FILLVAL: -9223372036854775808
  SCALETYP: linear
  LABLAXIS: Epoch delta
  DEPEND_0: epoch
pui_cooling_index:
  NAME: pui_cooling_index
  DATA_TYPE: CDF_REAL4
  FIELDNAM: PUI Cooling Index
  CATDESC: Pickup ion cooling index
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FORMAT: F19.3
  LABLAXIS: Cool Idx
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 5
  FILLVAL: -1.000000e+31
  SCALETYP: linear
  SCALEMIN: 0
  SCALEMAX: 5
  DELTA_PLUS_VAR: pui_cooling_index_uncert
  DELTA_MINUS_VAR: pui_cooling_index_uncert
pui_cooling_index_uncert:
  NAME: pui_cooling_index_uncert
  DATA_TYPE: CDF_REAL4
  FIELDNAM: PUI Cooling Index Uncertainty
  CATDESC: 1-sigma standard error
  LABLAXIS: Cool Idx Err
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: F19.3
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 5
  FILLVAL: -1.000000e+31
pui_ionization_rate:
  NAME: pui_ionization_rate
  DATA_TYPE: CDF_REAL4
  FIELDNAM: PUI Ionization Rate
  CATDESC: Pickup ion ionization rate
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FORMAT: E19.3
  LABLAXIS: Ion Rate
  UNITS: s^-1
  VALIDMIN: 0
  VALIDMAX: 1.0
  FILLVAL: -1.000000e+31
  SCALETYP: linear
  SCALEMIN: 0
  SCALEMAX: 9.0e-7
  DELTA_PLUS_VAR: pui_ionization_rate_uncert
  DELTA_MINUS_VAR: pui_ionization_rate_uncert
pui_ionization_rate_uncert:
  NAME: pui_ionization_rate_uncert
  DATA_TYPE: CDF_REAL4
  FIELDNAM: PUI Ionization Rate Uncertainty
  CATDESC: 1-sigma standard error
  LABLAXIS: Ion Rate Err
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: E19.3
  UNITS: s^-1
  VALIDMIN: 0
  VALIDMAX: 1.0
  FILLVAL: -1.000000e+31
pui_cutoff_speed:
  NAME: pui_cutoff_speed
  DATA_TYPE: CDF_REAL4
  FIELDNAM: PUI Cutoff Speed
  CATDESC: Pickup ion cutoff speed in the solar wind frame
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FORMAT: F19.3
  LABLAXIS: Cutoff V
  UNITS: km/s
  VALIDMIN: 0
  VALIDMAX: 10000
  FILLVAL: -1.000000e+31
  SCALETYP: linear
  SCALEMIN: 0
  SCALEMAX: 1000
  DELTA_PLUS_VAR: pui_cutoff_speed_uncert
  DELTA_MINUS_VAR: pui_cutoff_speed_uncert
pui_cutoff_speed_uncert:
  NAME: pui_cutoff_speed_uncert
  DATA_TYPE: CDF_REAL4
  FIELDNAM: PUI Cutoff Speed Uncertainty
  CATDESC: 1-sigma standard error
  LABLAXIS: Cutoff V Err
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: F19.3
  UNITS: km/s
  VALIDMIN: 0
  VALIDMAX: 10000
  FILLVAL: -1.000000e+31
pui_background_count_rate:
  NAME: pui_background_count_rate
  DATA_TYPE: CDF_REAL4
  FIELDNAM: PUI Background Count Rate
  CATDESC: Pickup ion background count rate
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FORMAT: E19.3
  LABLAXIS: Bg Rate
  UNITS: s^-1
  VALIDMIN: 0
  VALIDMAX: 9223372036854775807
  FILLVAL: -1.000000e+31
  SCALETYP: linear
  SCALEMIN: 0
  SCALEMAX: 0.2
  DELTA_PLUS_VAR: pui_background_count_rate_uncert
  DELTA_MINUS_VAR: pui_background_count_rate_uncert
pui_background_count_rate_uncert:
  NAME: pui_background_count_rate_uncert
  DATA_TYPE: CDF_REAL4
  FIELDNAM: PUI Background Count Rate Uncertainty
  CATDESC: 1-sigma standard error
  LABLAXIS: Bg Rate Err
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: E19.3
  UNITS: s^-1
  VALIDMIN: 0
  VALIDMAX: 1.0
  FILLVAL: -1.000000e+31
pui_density:
  NAME: pui_density
  DATA_TYPE: CDF_REAL4
  FIELDNAM: PUI Density
  CATDESC: Pickup ion number density
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FORMAT: E19.3
  LABLAXIS: n_PUI
  UNITS: cm^-3
  VALIDMIN: 0
  VALIDMAX: 1.0
  FILLVAL: -1.000000e+31
  SCALETYP: log
  SCALEMIN: 0.0001
  SCALEMAX: 0.0025
  DELTA_PLUS_VAR: pui_density_uncert
  DELTA_MINUS_VAR: pui_density_uncert
pui_density_uncert:
  NAME: pui_density_uncert
  DATA_TYPE: CDF_REAL4
  FIELDNAM: PUI Density Uncertainty
  CATDESC: 1-sigma standard error
  LABLAXIS: n_PUI Err
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: E19.3
  UNITS: cm^-3
  VALIDMIN: 0
  VALIDMAX: 1.0
  FILLVAL: -1.000000e+31
pui_temperature:
  NAME: pui_temperature
  DATA_TYPE: CDF_REAL4
  FIELDNAM: PUI Temperature
  CATDESC: Pickup ion temperature
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FORMAT: E19.3
  LABLAXIS: T_PUI
  UNITS: K
  VALIDMIN: 0
  VALIDMAX: 5.0e+7
  FILLVAL: -1.000000e+31
  SCALETYP: log
  SCALEMIN: 50000
  SCALEMAX: 50000000
  DELTA_PLUS_VAR: pui_temperature_uncert
  DELTA_MINUS_VAR: pui_temperature_uncert
pui_temperature_uncert:
  NAME: pui_temperature_uncert
  DATA_TYPE: CDF_REAL4
  FIELDNAM: PUI Temperature Uncertainty
  CATDESC: 1-sigma standard error
  LABLAXIS: T_PUI Err
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: E19.3
  UNITS: K
  VALIDMIN: 0
  VALIDMAX: 5.0e+7
  FILLVAL: -1.000000e+31
proton_sw_speed:
  NAME: proton_sw_speed
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Proton Solar Wind Speed
  CATDESC: Magnitude of the bulk velocity vector of the solar wind proton population (spacecraft frame)
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FORMAT: F19.3
  LABLAXIS: Vp SC
  UNITS: km/s
  VALIDMIN: 0
  VALIDMAX: 10000
  FILLVAL: -1.000000e+31
  SCALETYP: linear
  DELTA_PLUS_VAR: proton_sw_speed_uncert
  DELTA_MINUS_VAR: proton_sw_speed_uncert
  SCALEMIN: 0
  SCALEMAX: 1000
proton_sw_speed_uncert:
  NAME: proton_sw_speed_uncert
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Proton Solar Wind Speed Uncertainty
  CATDESC: 1-sigma standard error
  LABLAXIS: Vp SC Err
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: F19.3
  UNITS: km/s
  VALIDMIN: 0
  VALIDMAX: 10000
  FILLVAL: -1.000000e+31
proton_sw_speed_sun:
  NAME: proton_sw_speed_sun
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Proton Solar Wind Speed (Sun Frame)
  CATDESC: Magnitude of the bulk velocity vector of the solar wind proton population (Sun frame)
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FORMAT: F19.3
  LABLAXIS: Vp Sun
  UNITS: km/s
  VALIDMIN: 0
  VALIDMAX: 10000
  FILLVAL: -1.000000e+31
  SCALETYP: linear
  DELTA_PLUS_VAR: proton_sw_speed_sun_uncert
  DELTA_MINUS_VAR: proton_sw_speed_sun_uncert
  SCALEMIN: 0
  SCALEMAX: 1000
proton_sw_speed_sun_uncert:
  NAME: proton_sw_speed_sun_uncert
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Proton Solar Wind Speed Uncertainty (Sun Frame)
  CATDESC: 1-sigma standard error
  LABLAXIS: Vp Sun Err
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: F19.3
  UNITS: km/s
  VALIDMIN: 0
  VALIDMAX: 10000
  FILLVAL: -1.000000e+31
proton_sw_temperature:
  NAME: proton_sw_temperature
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Proton Solar Wind Temperature
  CATDESC: Scalar temperature of the solar wind proton population
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FORMAT: E19.3
  LABLAXIS: Tp
  UNITS: K
  VALIDMIN: 0
  VALIDMAX: 7000000
  FILLVAL: -1.000000e+31
  SCALETYP: log
  DELTA_PLUS_VAR: proton_sw_temperature_uncert
  DELTA_MINUS_VAR: proton_sw_temperature_uncert
  SCALEMIN: 1000
  SCALEMAX: 240000
proton_sw_temperature_uncert:
  NAME: proton_sw_temperature_uncert
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Proton Solar Wind Temperature Uncertainty
  CATDESC: 1-sigma standard error
  LABLAXIS: Tp Err
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: E19.3
  UNITS: K
  VALIDMIN: 0
  VALIDMAX: 7000000
  FILLVAL: -1.000000e+31
proton_sw_density:
  NAME: proton_sw_density
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Proton Solar Wind Density
  CATDESC: Number density of the solar wind proton population
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FORMAT: E19.3
  LABLAXIS: Np
  UNITS: cm^-3
  VALIDMIN: 0
  VALIDMAX: 150
  FILLVAL: -1.000000e+31
  SCALETYP: log
  DELTA_PLUS_VAR: proton_sw_density_uncert
  DELTA_MINUS_VAR: proton_sw_density_uncert
  SCALEMIN: 0.1
  SCALEMAX: 16
proton_sw_density_uncert:
  NAME: proton_sw_density_uncert
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Proton Solar Wind Density Uncertainty
  CATDESC: 1-sigma standard error
  LABLAXIS: Np Err
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: E19.3
  UNITS: cm^-3
  VALIDMIN: 0
  VALIDMAX: 150
  FILLVAL: -1.000000e+31
proton_sw_velocity_rtn_sun:
  NAME: proton_sw_velocity_rtn_sun
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Proton Solar Wind Velocity (RTN, Sun Frame)
  CATDESC: Solar wind proton bulk velocity vector in RTN coordinates (Sun frame)
  DEPEND_0: epoch
  LABL_PTR_1: proton_sw_velocity_rtn_sun_label
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FORMAT: F19.3
  LABLAXIS: Vp RTN Sun
  UNITS: km/s
  VALIDMIN: -10000
  VALIDMAX: 10000
  FILLVAL: -1.000000e+31
  SCALETYP: linear
  DELTA_PLUS_VAR: proton_sw_velocity_rtn_uncert
  DELTA_MINUS_VAR: proton_sw_velocity_rtn_uncert
proton_sw_velocity_rtn:
  NAME: proton_sw_velocity_rtn
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Proton Solar Wind Velocity (RTN)
  CATDESC: Solar wind proton bulk velocity vector in RTN coordinates (spacecraft frame)
  DEPEND_0: epoch
  LABL_PTR_1: proton_sw_velocity_rtn_label
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FORMAT: F19.3
  LABLAXIS: Vp RTN SC
  UNITS: km/s
  VALIDMIN: -10000
  VALIDMAX: 10000
  FILLVAL: -1.000000e+31
  SCALETYP: linear
  DELTA_PLUS_VAR: proton_sw_velocity_rtn_uncert
  DELTA_MINUS_VAR: proton_sw_velocity_rtn_uncert
proton_sw_velocity_rtn_covariance:
  NAME: proton_sw_velocity_rtn_covariance
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Proton Solar Wind Velocity Covariance (RTN)
  CATDESC: Covariance matrix in RTN coordinates (frame-independent), with standard errors given by the square root of the diagonal
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: F19.3
  LABLAXIS: cov Vp
  UNITS: km^2/s^2
  VALIDMIN: -1.0e+8
  VALIDMAX: 1.0e+8
  FILLVAL: -1.000000e+31
  LABL_PTR_1: velocity_rtn_label
  LABL_PTR_2: velocity_rtn_label
proton_sw_velocity_rtn_uncert:
  NAME: proton_sw_velocity_rtn_uncert
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Proton Solar Wind Velocity Uncertainty (RTN)
  CATDESC: 1-sigma standard error
  DEPEND_0: epoch
  LABL_PTR_1: velocity_rtn_label
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: F19.3
  LABLAXIS: Vp RTN Err
  UNITS: km/s
  VALIDMIN: 0
  VALIDMAX: 10000
  FILLVAL: -1.000000e+31
  SCALETYP: linear
alpha_sw_speed:
  NAME: alpha_sw_speed
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Alpha Solar Wind Speed
  CATDESC: Magnitude of the bulk velocity vector of the solar wind alpha-particle population (spacecraft frame)
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FORMAT: F19.3
  LABLAXIS: Va SC
  UNITS: km/s
  VALIDMIN: 0
  VALIDMAX: 10000
  FILLVAL: -1.000000e+31
  SCALETYP: linear
  DELTA_PLUS_VAR: alpha_sw_speed_uncert
  DELTA_MINUS_VAR: alpha_sw_speed_uncert
  SCALEMIN: 0
  SCALEMAX: 1000
alpha_sw_speed_uncert:
  NAME: alpha_sw_speed_uncert
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Alpha Solar Wind Speed Uncertainty
  CATDESC: 1-sigma standard error
  LABLAXIS: Va SC Err
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: F19.3
  UNITS: km/s
  VALIDMIN: 0
  VALIDMAX: 10000
  FILLVAL: -1.000000e+31
alpha_sw_speed_sun:
  NAME: alpha_sw_speed_sun
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Alpha Solar Wind Speed (Sun Frame)
  CATDESC: Magnitude of the bulk velocity vector of the solar wind alpha-particle population (Sun frame)
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FORMAT: F19.3
  LABLAXIS: Va Sun
  UNITS: km/s
  VALIDMIN: 0
  VALIDMAX: 10000
  FILLVAL: -1.000000e+31
  SCALETYP: linear
  DELTA_PLUS_VAR: alpha_sw_speed_sun_uncert
  DELTA_MINUS_VAR: alpha_sw_speed_sun_uncert
  SCALEMIN: 0
  SCALEMAX: 1000
alpha_sw_speed_sun_uncert:
  NAME: alpha_sw_speed_sun_uncert
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Alpha Solar Wind Speed Uncertainty (Sun Frame)
  CATDESC: 1-sigma standard error
  LABLAXIS: Va Sun Err
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: F19.3
  UNITS: km/s
  VALIDMIN: 0
  VALIDMAX: 10000
  FILLVAL: -1.000000e+31
alpha_sw_temperature:
  NAME: alpha_sw_temperature
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Alpha Solar Wind Temperature
  CATDESC: Scalar temperature of the solar wind alpha-particle population
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FORMAT: E19.3
  LABLAXIS: Ta
  UNITS: K
  VALIDMIN: 0
  VALIDMAX: 28000000
  FILLVAL: -1.000000e+31
  SCALETYP: log
  DELTA_PLUS_VAR: alpha_sw_temperature_uncert
  DELTA_MINUS_VAR: alpha_sw_temperature_uncert
  SCALEMIN: 4000
  SCALEMAX: 960000
alpha_sw_temperature_uncert:
  NAME: alpha_sw_temperature_uncert
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Alpha Solar Wind Temperature Uncertainty
  CATDESC: 1-sigma standard error
  LABLAXIS: Ta Err
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: E19.3
  UNITS: K
  VALIDMIN: 0
  VALIDMAX: 28000000
  FILLVAL: -1.000000e+31
alpha_sw_density:
  NAME: alpha_sw_density
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Alpha Solar Wind Density
  CATDESC: Number density of the solar wind alpha-particle population
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FORMAT: E19.3
  LABLAXIS: Na
  UNITS: cm^-3
  VALIDMIN: 0
  VALIDMAX: 100
  FILLVAL: -1.000000e+31
  SCALETYP: log
  DELTA_PLUS_VAR: alpha_sw_density_uncert
  DELTA_MINUS_VAR: alpha_sw_density_uncert
  SCALEMIN: 0.001
  SCALEMAX: 5
alpha_sw_density_uncert:
  NAME: alpha_sw_density_uncert
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Alpha Solar Wind Density Uncertainty
  CATDESC: 1-sigma standard error
  LABLAXIS: Na Err
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: E19.3
  UNITS: cm^-3
  VALIDMIN: 0
  VALIDMAX: 100
  FILLVAL: -1.000000e+31
alpha_sw_velocity_rtn_sun:
  NAME: alpha_sw_velocity_rtn_sun
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Alpha Solar Wind Velocity (RTN, Sun Frame)
  CATDESC: Solar wind alpha-particle bulk velocity vector in RTN coordinates (Sun frame)
  DEPEND_0: epoch
  LABL_PTR_1: alpha_sw_velocity_rtn_sun_label
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FORMAT: F19.3
  LABLAXIS: Va RTN Sun
  UNITS: km/s
  VALIDMIN: -10000
  VALIDMAX: 10000
  FILLVAL: -1.000000e+31
  SCALETYP: linear
  DELTA_PLUS_VAR: alpha_sw_velocity_rtn_uncert
  DELTA_MINUS_VAR: alpha_sw_velocity_rtn_uncert
alpha_sw_velocity_rtn:
  NAME: alpha_sw_velocity_rtn
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Alpha Solar Wind Velocity (RTN)
  CATDESC: Solar wind alpha-particle bulk velocity vector in RTN coordinates (spacecraft frame)
  DEPEND_0: epoch
  LABL_PTR_1: alpha_sw_velocity_rtn_label
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FORMAT: F19.3
  LABLAXIS: Va RTN SC
  UNITS: km/s
  VALIDMIN: -10000
  VALIDMAX: 10000
  FILLVAL: -1.000000e+31
  SCALETYP: linear
  DELTA_PLUS_VAR: alpha_sw_velocity_rtn_uncert
  DELTA_MINUS_VAR: alpha_sw_velocity_rtn_uncert
alpha_sw_velocity_rtn_covariance:
  NAME: alpha_sw_velocity_rtn_covariance
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Alpha Solar Wind Velocity Covariance (RTN)
  CATDESC: Covariance matrix in RTN coordinates (frame-independent), with standard errors given by the square root of the diagonal
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: F19.3
  LABLAXIS: cov Va
  UNITS: km^2/s^2
  VALIDMIN: -1.0e+8
  VALIDMAX: 1.0e+8
  FILLVAL: -1.000000e+31
  LABL_PTR_1: velocity_rtn_label
  LABL_PTR_2: velocity_rtn_label
alpha_sw_velocity_rtn_uncert:
  NAME: alpha_sw_velocity_rtn_uncert
  DATA_TYPE: CDF_REAL4
  FIELDNAM: Alpha Solar Wind Velocity Uncertainty (RTN)
  CATDESC: 1-sigma standard error
  DEPEND_0: epoch
  LABL_PTR_1: velocity_rtn_label
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FORMAT: F19.3
  LABLAXIS: Va RTN Err
  UNITS: km/s
  VALIDMIN: 0
  VALIDMAX: 10000
  FILLVAL: -1.000000e+31
  SCALETYP: linear
swp_flags:
  NAME: swp_flags
  DATA_TYPE: CDF_UINT2
  FIELDNAM: Quality Flags for SWAPI L3a
  CATDESC: "Quality flags for SWAPI L3a (caution required if nonzero)"
  DEPEND_0: epoch
  VAR_TYPE: data
  DISPLAY_TYPE: time_series
  SCALETYP: linear
  RECORD_VARYING: RV
  FORMAT: I5
  UNITS: '0: okay; nonzero: caution'
  VALIDMIN: 0
  VALIDMAX: 65534
  FILLVAL: 65535
  LABLAXIS: Quality flags for SWAPI L3a
  VAR_NOTES: >-
    Each bit corresponds to a specific potential concern. See release notes for details.
    Bit 2: Bad fit: fitting resulted in invalid values or large residuals.
    Bit 3: Fit error: fit failed to complete.
    Bit 4: preliminary MAG L1D was used for acquiring the magnetic field direction instead of the nominal MAG L2 product.
    Bit 15: indicates predictive ephemeris was used instead of reconstructed ephemeris.
    All other bits are reserved.
velocity_rtn_label:
  NAME: velocity_rtn_label
  DATA_TYPE: CDF_CHAR
  FIELDNAM: Velocity RTN Label
  CATDESC: Label for Radial-Tangential-Normal (RTN) velocity components
  VAR_TYPE: metadata
  RECORD_VARYING: NRV
  FORMAT: a20
  FILLVAL: ' '
alpha_sw_velocity_rtn_label:
  NAME: alpha_sw_velocity_rtn_label
  DATA_TYPE: CDF_CHAR
  FIELDNAM: Velocity RTN Label
  CATDESC: Label for Radial-Tangential-Normal (RTN) velocity components
  VAR_TYPE: metadata
  RECORD_VARYING: NRV
  FORMAT: a20
  FILLVAL: ' '
alpha_sw_velocity_rtn_sun_label:
  NAME: alpha_sw_velocity_rtn_sun_label
  DATA_TYPE: CDF_CHAR
  FIELDNAM: Velocity RTN Label
  CATDESC: Label for Radial-Tangential-Normal (RTN) velocity components
  VAR_TYPE: metadata
  RECORD_VARYING: NRV
  FORMAT: a20
  FILLVAL: ' '
proton_sw_velocity_rtn_label:
  NAME: proton_sw_velocity_rtn_label
  DATA_TYPE: CDF_CHAR
  FIELDNAM: Velocity RTN Label
  CATDESC: Label for Radial-Tangential-Normal (RTN) velocity components
  VAR_TYPE: metadata
  RECORD_VARYING: NRV
  FORMAT: a20
  FILLVAL: ' '
proton_sw_velocity_rtn_sun_label:
  NAME: proton_sw_velocity_rtn_sun_label
  DATA_TYPE: CDF_CHAR
  FIELDNAM: Velocity RTN Label
  CATDESC: Label for Radial-Tangential-Normal (RTN) velocity components
  VAR_TYPE: metadata
  RECORD_VARYING: NRV
  FORMAT: a20
  FILLVAL: ' '

