epoch:
  NAME: epoch
  DATA_TYPE: CDF_TIME_TT2000
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Epoch
  FORMAT: ' '
  LABLAXIS: Epoch
  UNITS: ns
  VALIDMIN: 1990-01-01T00:00:00.000000000
  VALIDMAX: 2099-12-31T00:00:00.000000000
  FILLVAL: 9999-12-31T23:59:59.999999999
  TIME_BASE: J2000
  TIME_SCALE: TT
  DELTA_PLUS_VAR: epoch_delta
  DELTA_MINUS_VAR: epoch_delta
  MONOTON: INCREASE
  REFERENCE_POSITION: Rotating Earth Geoid
  SCALETYP: linear
  SI_CONVERSION: 1e-9>seconds
epoch_delta:
  NAME: epoch_delta
  DATA_TYPE: CDF_INT8
  CATDESC: Epoch delta
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Epoch Delta
  FORMAT: I19
  LABLAXIS: Epoch delta
  UNITS: ns
  VALIDMIN: 0
  VALIDMAX: 86000000000000
  FILLVAL: -9223372036854775808
  DEPEND_0: epoch
  SCALETYP: linear
charge:
  NAME: charge
  DATA_TYPE: CDF_FLOAT
  CATDESC: Particle atomic charge (element) estimate (float)
  VAR_TYPE: data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Charge
  FORMAT: F15.3
  LABLAXIS: Charge
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 200
  FILLVAL: -1.00E+31
energy:
  NAME: energy
  DATA_TYPE: CDF_FLOAT
  CATDESC: Energy (sum of all delta-Es with cosine correction)
  VAR_TYPE: data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Energy
  FORMAT: F15.3
  LABLAXIS: Energy
  UNITS: MeV
  VALIDMIN: 0.1
  VALIDMAX: 10000
  FILLVAL: -1.00E+31
  SCALEMIN: 0.1
  SCALEMAX: 10000
energy_in_detector:
  NAME: energy_in_detector
  DATA_TYPE: CDF_FLOAT
  CATDESC: Energy in detector (delta-E in detector_id detector with cosine correction)
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DEPEND_1: detector_id
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Energy In Detector
  FORMAT: F15.3
  LABLAXIS: Detector delta-E
  UNITS: MeV
  VALIDMIN: 0.1
  VALIDMAX: 10000
  FILLVAL: -1.00E+31
  SCALEMIN: 0.1
  SCALEMAX: 10000
range:
  NAME: range
  DATA_TYPE: CDF_UINT1
  CATDESC: Particle range (2 = L1L2, 3=L1L2L3, 4=L1L2L3L3)
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: timeseries
  FIELDNAM: Range
  FORMAT: I4
  LABLAXIS: Range
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 4
  FILLVAL: 255
delta_e:
  NAME: delta_e
  DATA_TYPE: CDF_FLOAT
  CATDESC: Delta E (energy deposited in detector that particle fully penetrates)
  VAR_TYPE: data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Delta E
  FORMAT: F15.3
  LABLAXIS: Delta E
  UNITS: MeV
  VALIDMIN: 0.1
  VALIDMAX: 10000
  FILLVAL: -1.00E+31
  SCALEMIN: 0.1
  SCALEMAX: 10000
e_prime:
  NAME: e_prime
  DATA_TYPE: CDF_FLOAT
  CATDESC: E prime (energy deposited in stopping detector)
  VAR_TYPE: data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: E Prime
  FORMAT: F15.3
  LABLAXIS: E prime
  UNITS: MeV
  VALIDMIN: 0.1
  VALIDMAX: 10000
  FILLVAL: -1.00E+31
  SCALEMIN: 0.1
  SCALEMAX: 10000
particle_id:
  NAME: particle_id
  DATA_TYPE: CDF_UINT2
  CATDESC: Particle Id (instrument internal identification number)
  VAR_TYPE: data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: Particle Id
  LABLAXIS: Particle Id
  FORMAT: I3
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 255
  FILLVAL: 65535
priority_buffer_number:
  NAME: priority_buffer_number
  DATA_TYPE: CDF_UINT1
  CATDESC: Priority buffer number (instrument has multiple buffers to prioritize events to be transmitted to ground)
  VAR_TYPE: data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: Priority Buffer Number
  LABLAXIS: Priority Buffer Number
  FORMAT: I3
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 254
  FILLVAL: 255
latency:
  NAME: latency
  DATA_TYPE: CDF_UINT1
  CATDESC: Latency (delay between particle entering and leaving priority buffer)
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: Latency
  FORMAT: I2
  LABLAXIS: Latency
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 16
  FILLVAL: 255
stim_tag:
  NAME: stim_tag
  DATA_TYPE: CDF_INT1
  CATDESC: Stim tag (1 = indicates stimulus event, charge from pulsers not real event)
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: Stim Tag
  FORMAT: I1
  LABLAXIS: "Stim tag"
  UNITS: '1=not real event'
  VALIDMIN: 0
  VALIDMAX: 1
  FILLVAL: -128
long_event_flag:
  NAME: long_event_flag
  DATA_TYPE: CDF_INT1
  CATDESC: Long event flag (1 if extra fields in transmitted event)
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: Long Event Flag
  FORMAT: I1
  LABLAXIS: "Long event"
  UNITS: '1=extra fields'
  VALIDMIN: 0
  VALIDMAX: 1
  FILLVAL: -128
haz_tag:
  NAME: haz_tag
  DATA_TYPE: CDF_INT1
  CATDESC: Haz tag (hazard, 1 if second event occurred too soon after first event)
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: Haz Tag
  FORMAT: I1
  LABLAXIS: "Hazard"
  UNITS: '1=second coincidence'
  VALIDMIN: 0
  VALIDMAX: 1
  FILLVAL: -128
side:
  NAME: side
  DATA_TYPE: CDF_INT1
  CATDESC: A B side (0 = A-side, opposite Sun, 1 = B-side, sunward)
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: A B Side
  FORMAT: I1
  LABLAXIS: "Side"
  UNITS: '0=A 1=B'
  VALIDMIN: 0
  VALIDMAX: 1
  FILLVAL: -128
has_unread_flag:
  NAME: has_unread_flag
  DATA_TYPE: CDF_INT1
  CATDESC: Has unread flag (1 if not all triggered PHA channels transmitted with event)
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: Has Unread Flag
  FORMAT: I1
  LABLAXIS: "Unread"
  UNITS: '1=not all channels transmitted'
  VALIDMIN: 0
  VALIDMAX: 1
  FILLVAL: -128
culling_flag:
  NAME: culling_flag
  DATA_TYPE: CDF_INT1
  CATDESC: Culling flag (1 if onboard DPU removed some PHA channels)
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: Culling Flag
  FORMAT: I1
  LABLAXIS: Culling
  UNITS: '1=channels removed onboard'
  VALIDMIN: 0
  VALIDMAX: 1
  FILLVAL: -128
pha_value:
  NAME: pha_value
  DATA_TYPE: CDF_UINT2
  CATDESC: Pha value (raw pulse height value)
  VAR_TYPE: data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DEPEND_1: detector_id
  DISPLAY_TYPE: spectrogram
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Pha Value
  FORMAT: I8
  LABLAXIS: PHA value
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 65534
  FILLVAL: 65535
is_low_gain:
  NAME: is_low_gain
  DATA_TYPE: CDF_INT1
  CATDESC: Is low gain (1 if pha_value is from low-gain channel)
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DEPEND_1: detector_id
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Is Low Gain
  FORMAT: I1
  LABLAXIS: "Low Gain"
  UNITS: '1=from low-gain channel'
  VALIDMIN: 0
  VALIDMAX: 1
  FILLVAL: -128
detector_flags:
  NAME: detector_flags
  DATA_TYPE: CDF_UINT2
  CATDESC: Detector flags (bit 0 = L1A, 1 = L2A, 2 = L3A, 3 = L1B, 4 = L2B, 5 = L3B, 6 = L4A, 7 = L4B)
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: Detector Flags
  FORMAT: I5
  LABLAXIS: Detector Flags
  UNITS: 'bit 0=L1A 1=L2A 2=L3A 3=L1B 4=L2B 5=L3B 6=L4A 7=L4B'
  VALIDMIN: 0
  VALIDMAX: 65534
  FILLVAL: 65535
deindex:
  NAME: deindex
  DATA_TYPE: CDF_UINT2
  CATDESC: Index of delta E
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: Deindex
  FORMAT: I3
  LABLAXIS: dE Index
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 399
  FILLVAL: 65535
epindex:
  NAME: epindex
  DATA_TYPE: CDF_UINT2
  CATDESC: Index of E prime
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: Epindex
  FORMAT: I3
  LABLAXIS: Ep Index
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 127
  FILLVAL: 65535
stim_gain:
  NAME: stim_gain
  DATA_TYPE: CDF_INT1
  CATDESC: Stim gain (gain of pulser for stim) 0=high 1=low
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: Stim Gain
  FORMAT: I1
  LABLAXIS: Stim Gain
  UNITS: '0=high 1=low'
  VALIDMIN: 0
  VALIDMAX: 1
  FILLVAL: -128
a_l_stim:
  NAME: a_l_stim
  DATA_TYPE: CDF_INT1
  CATDESC: A L stim (0 = ADC stim event, 1 = livetime stim event)
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: A L Stim
  FORMAT: I1
  LABLAXIS: A L Stim
  UNITS: '0=ADC 1=livetime'
  VALIDMIN: 0
  VALIDMAX: 1
  FILLVAL: -128
stim_step:
  NAME: stim_step
  DATA_TYPE: CDF_UINT1
  CATDESC: Stim step (index of table of stim steps)
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: Stim Step
  FORMAT: I3
  LABLAXIS: Stim Step
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 254
  FILLVAL: 255
dac_value:
  NAME: dac_value
  DATA_TYPE: CDF_UINT2
  CATDESC: Dac value (pulser dac that controls voltage)
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: Dac Value
  FORMAT: I5
  LABLAXIS: Dac Value
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 10000
  FILLVAL: 65535
detector_id:
  NAME: detector_id
  DATA_TYPE: CDF_UINT1
  CATDESC: index used to support up to 64 detector addresses per event
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: Detector Id
  FORMAT: I4
  LABLAXIS: Detector Id
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 64
  FILLVAL: 255
hit_flags:
  NAME: hit_flags
  DATA_TYPE: CDF_UINT2
  CATDESC: "Quality flags for HIT L3 direct events (caution required if nonzero)"
  DEPEND_0: epoch
  VAR_TYPE: data
  DISPLAY_TYPE: time_series
  SCALETYP: linear
  RECORD_VARYING: RV
  FIELDNAM: Quality Flags for HIT L3 direct events
  FORMAT: I5
  UNITS: '0: okay; nonzero: caution'
  VALIDMIN: 0
  VALIDMAX: 65534
  FILLVAL: 65535
  LABLAXIS: Quality flags for HIT L3 direct events
  VAR_NOTES: >-
    Each bit corresponds to a specific potential concern. See release notes for details.
    Other bits are reserved.
