epoch:
  NAME: epoch
  DATA_TYPE: CDF_TIME_TT2000
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included for center of CR
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Epoch
  FORMAT: ' '
  LABLAXIS: Epoch
  UNITS: ns
  VALIDMIN: 2010-01-01T00:00:00.000000000
  VALIDMAX: 2099-12-31T00:00:00.000000000
  FILLVAL: 9999-12-31T23:59:59.999999999
  SCALETYP: linear
  TIME_BASE: J2000
  TIME_SCALE: TT
  DELTA_PLUS_VAR: epoch_delta
  DELTA_MINUS_VAR: epoch_delta
  MONOTON: INCREASE
  REFERENCE_POSITION: Rotating Earth Geoid
  SI_CONVERSION: 1e-9>seconds
epoch_delta:
  NAME: epoch_delta
  DATA_TYPE: CDF_INT8
  CATDESC: Time bin of half a carrington rotation
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Epoch Delta
  FORMAT: I19
  LABLAXIS: Epoch delta
  UNITS: ns
  VALIDMIN: 0
  VALIDMAX: 2592000000000000
  FILLVAL: -9223372036854775808
  SCALETYP: linear
mean_time:
  NAME: mean_time
  DATA_TYPE: CDF_TIME_TT2000
  CATDESC: Mean time of lightcurve data, number of nanoseconds since J2000 with leap seconds
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Mean Time
  FORMAT: ' '
  LABLAXIS: Mean Time
  UNITS: ns
  VALIDMIN: 2010-01-01T00:00:00.000000000
  VALIDMAX: 2099-12-31T00:00:00.000000000
  FILLVAL: 9999-12-31T23:59:59.999999999
  SCALETYP: linear
  TIME_BASE: J2000
  TIME_SCALE: TT
  MONOTON: INCREASE
  REFERENCE_POSITION: Rotating Earth Geoid
  SI_CONVERSION: 1e-9>seconds
cr:
  NAME: cr
  DATA_TYPE: CDF_INT2
  CATDESC: Carrington rotation number
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Carrington Rotation
  FORMAT: I14
  LABLAXIS: Carrington rotation
  UNITS: ' '
  VALIDMIN: 2000
  VALIDMAX: 3000
  FILLVAL: -32768
  SCALETYP: linear
plasma_speed_ecliptic:
  NAME: plasma_speed_ecliptic
  DATA_TYPE: CDF_FLOAT
  CATDESC: Averaged solar wind plasma speed in the ecliptic plane
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Ecliptic Plasma Speed
  FORMAT: F9.3
  LABLAXIS: Ecliptic Plasma Speed
  UNITS: km/s
  VALIDMIN: 0
  VALIDMAX: 10000.0
  FILLVAL: -1.00E+31
  SCALETYP: linear
  SCALEMIN: 0
  SCALEMAX: 1000.0
  SI_CONVERSION: 1e3>m/s
lat_grid:
  NAME: lat_grid
  DATA_TYPE: CDF_FLOAT
  CATDESC: Latitudinal grid from -90 to 90
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: Latitude Grid
  FORMAT: F9.3
  LABLAXIS: Lat grid
  UNITS: degrees
  VALIDMIN: -90
  VALIDMAX: 90
  FILLVAL: -1.00E+31
  LABL_PTR_1: lat_grid_label
  SCALETYP: linear
lat_grid_label:
  NAME: lat_grid_label
  DATA_TYPE: CDF_CHAR
  CATDESC: Label for lat grid
  VAR_TYPE: metadata
  FIELDNAM: lat Grid Label
  FORMAT: a20
  FILLVAL: ' '
proton_density_ecliptic:
  NAME: proton_density_ecliptic
  DATA_TYPE: CDF_FLOAT
  CATDESC: Averaged proton density in the ecliptic plane adjusted to 1 au
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Ecliptic Proton Density
  FORMAT: F12.3
  LABLAXIS: Ecliptic Proton Density
  UNITS: cm^-3
  VALIDMIN: 0
  VALIDMAX: 1.0e+6
  FILLVAL: -1.00E+31
  SCALETYP: linear
  SCALEMIN: 0
  SCALEMAX: 10.0
  SI_CONVERSION: 1e6>m^-3
alpha_abundance_ecliptic:
  NAME: alpha_abundance_ecliptic
  DATA_TYPE: CDF_FLOAT
  CATDESC: Averaged alpha-particles to protons ratio in the ecliptic plane
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Alpha Abundance
  FORMAT: F9.3
  LABLAXIS: Abundance
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 1.0
  FILLVAL: -1.00E+31
  SCALETYP: linear
  SCALEMIN: 0
  SCALEMAX: 0.02
plasma_speed_profile:
  NAME: plasma_speed_profile
  DATA_TYPE: CDF_FLOAT
  CATDESC: Averaged profile of solar wind plasma speed
  DEPEND_0: epoch
  DEPEND_1: lat_grid
  VAR_NOTES: "Calculated directly at the grid point; not integrated over space"
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: spectrogram
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Plasma Speed Profile
  FORMAT: F9.3
  LABLAXIS: Plasma Speed
  UNITS: km/s
  VALIDMIN: 0
  VALIDMAX: 10000.0
  FILLVAL: -1.00E+31
  LABL_PTR_1: lat_grid_label
  SCALETYP: linear
  SCALEMIN: 0
  SCALEMAX: 1000.0
  SI_CONVERSION: 1e3>m/s
proton_density_profile:
  NAME: proton_density_profile
  DATA_TYPE: CDF_FLOAT
  CATDESC: Averaged profile of proton density adjusted to 1 au
  DEPEND_0: epoch
  DEPEND_1: lat_grid
  VAR_NOTES: "Calculated directly at the grid point; not integrated over space"
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: spectrogram
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Proton Density Profile
  FORMAT: F12.3
  LABLAXIS: Proton Density
  UNITS: cm^-3
  VALIDMIN: 0
  VALIDMAX: 1.0e+6
  FILLVAL: -1.00E+31
  LABL_PTR_1: lat_grid_label
  SCALETYP: linear
  SCALEMIN: 0
  SCALEMAX: 10.0
  SI_CONVERSION: 1e6>m^-3
glows_flags:
  NAME: glows_flags
  DATA_TYPE: CDF_UINT2
  CATDESC: "Quality flags for GLOWS L3c (caution required if nonzero)"
  DEPEND_0: epoch
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series
  SCALETYP: linear
  FIELDNAM: Quality Flags for GLOWS L3c
  FORMAT: I5
  UNITS: '0: okay; nonzero: caution'
  VALIDMIN: 0
  VALIDMAX: 65534
  FILLVAL: 65535
  LABLAXIS: Quality flags for GLOWS L3c
  VAR_NOTES: >-
    Each bit corresponds to a specific potential concern. See release notes for details.
    Bit 2: Solar wind alpha/proton density ratio not available in OMNI data; used nominal value of 0.04
    Other bits are reserved.
